services:
  db:
    image: postgres:17
    container_name: skolkovo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: skolkovo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skolkovo"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skolkovo-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3400
      DB_SERVERNAME: postgres
      DB_PASSWORD: 1
      DB_NAME: skolkovo
      DB_HOST: db
      DB_PORT: 5433
      SALT_ROUNDS: 10
      JWT_ACCESS_SECRET_KEY: skolkovo_access_qwerty_123455_hgsdfjh8rw234d1a4s1a4j1987
      JWT_REFRESH_SECRET_KEY: skolkovo_refresh_qwerty_123455_8793405ds1324h8ff657f45f
      TG_AUTH_SECRET_KEY: 34dfgB8dK98bdr34dGsfvrtfhj768576ndgfdg&Vp&7ccfughurisechner
      TG_BOT_API_BASE_URL: https://api-bot.skolkovo.ru/server-api/v1
      TG_BOT_API_TOKEN: jhsdfgkfdsjgfdsigfsdiogsdffgdt45.unjkghfsd8432tnjdksfhg89345w12sdlkfhasd.uir8916b7tubys7ehjasdhjgafd
    ports:
      - "3400:3400"
    volumes:
      - static_data:/app/static

volumes:
  postgres_data:
  static_data:
